[build]
  publish = "src"
  command = "# no build command needed for static site"

[build.environment]
  NODE_VERSION = "16"

# Redirect all URLs to index.html for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set custom headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://kit.fontawesome.com 'unsafe-inline'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com https://ka-f.fontawesome.com; img-src 'self' data:; connect-src 'self'" 